# Default values for iap-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

cloudSA:
  secretName:
  secretKey:

oauthSecret:

image:
  repository: python
  tag: 2.7
  pullPolicy: IfNotPresent

kube-lego:
  enabled: false
  config:
## REQUIRED must be set to a valid email
    LEGO_EMAIL:
#   Set to https://acme-v01.api.letsencrypt.org/directory for "real" certs
    LEGO_URL: https://acme-staging.api.letsencrypt.org/directory
    LEGO_SECRET_NAME: lego-acme

kube-metacontroller:
  enabled: false