apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    component: zeppelin
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: web
  selector:
    app: {{ template "fullname" . }}