# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image: danisla/hadoop:2.7.3
imagePullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 2.7.3

# Select anitAffinity as either hard or soft, default is hard
antiAffinity: "hard"

hdfs:
  nameNode:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: "1024Mi"
        cpu: "200m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

    persistentVolume:
      enabled: false
      storageClassName: standard
      accessMode: ReadWriteOnce 
      size: 50Gi

  dataNode:
    replicas: 2

    pdbMinAvailable: 1

    resources:
      requests:
        memory: "1024Mi"
        cpu: "200m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

    persistentVolume:
      enabled: false
      storageClassName: standard
      accessMode: ReadWriteOnce 
      size: 100Gi

yarn:
  resourceManager:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: "1024Mi"
        cpu: "200m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"

  nodeManager:
    pdbMinAvailable: 1

    # The number of YARN NodeManager instances.
    replicas: 2

    # CPU and memory resources allocated to each node manager pod.
    # This should be tuned to fit your workload.
    resources:
      limits:
        memory: "2048Mi"
        cpu: "1000m"