# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-yarn-nm
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: yarn-nm
spec:
  ports:
  - port: 8088
    name: web
  - port: 8082
    name: web2
  - port: 8042
    name: api
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
    component: yarn-nm